name = "Simple Resume"
license = "MIT"
licenselink = "https://github.com/tylerjlawson/simple-resume/blob/master/LICENSE"
description = "This is a simple resume that you can print or host on the web"
homepage = "https://github.com/tylerjlawson/simple-resume/"
tags = ["cv", "resume", "minimalist"]
min_version = "0.41.0"
demosite = "https://focused-varahamihira-bdb0c9.netlify.app/"

[author]
  name = "Tyler Lawson"
  homepage = "https://tyler-lawson.com"
